# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

namespacePermissions:
  # Which OpenShift user gets permissions for the namespace
  user: user0
  # Which role to grant the user on the namespace
  role: admin

vm:
  name: rhel-user0
  datasourcename: rhel10
  datasourcenamespace: openshift-virtualization-os-images
  username: rhel
  password: password
  disksize: 30Gi
  instancetype: u1.medium
  ssh_pwauth: true
  init_script: ""
  # init_script: https://raw.githubusercontent.com/rhpds/zero-cve-hummingbird-showroom/refs/heads/main/scripts/init-vm.sh

datavolume:
  name: hummingbird
  namespace: openshift-virtualization-os-images
  source: http://url_to_qcow2_image.qcow2
  storageClassName: ocs-external-storagecluster-ceph-rbd-immediate
  disksize: 30Gi

datasource:
  name: hummingbird
  namespace: openshift-virtualization-os-images
  source:
    name: hummingbird-image
    namespace: openshift-virtualization-os-images
