apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kai-api-keys
spec:
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: kai-api-keys
  data:
    - secretKey: OPENAI_API_BASE
      remoteRef:
        key: secrets/mta/llm
        property: base_url
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: secrets/mta/llm
        property: api_key
