---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  name: {{ .Values.datasource.name }}
  namespace: {{ .Values.datasource.namespace }}
spec:
  source:
    pvc:
      name: {{ .Values.datasource.source.name }}
      namespace: {{ .Values.datasource.source.namespace }}
